# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP31",
  "description": "Датчик в комнате"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensor/2/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor_id": 3,
  "temperature":26.6
}

###

# получение информации по датчику
GET {{baseUrl}}/sensor/2/
Content-Type: application/json
